// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sgapca_exC
Rcpp::List sgapca_exC(const arma::colvec& ds, const arma::mat& Qs, const arma::colvec& x, const arma::colvec& gamma);
RcppExport SEXP onlinePCA_sgapca_exC(SEXP dsSEXP, SEXP QsSEXP, SEXP xSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const arma::colvec& >::type ds(dsSEXP );
        Rcpp::traits::input_parameter< const arma::mat& >::type Qs(QsSEXP );
        Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP );
        Rcpp::traits::input_parameter< const arma::colvec& >::type gamma(gammaSEXP );
        Rcpp::List __result = sgapca_exC(ds, Qs, x, gamma);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// sgapca_nnC
Rcpp::List sgapca_nnC(const arma::colvec& ds, const arma::mat& Q, const arma::colvec& x, const arma::colvec& gamma);
RcppExport SEXP onlinePCA_sgapca_nnC(SEXP dsSEXP, SEXP QSEXP, SEXP xSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const arma::colvec& >::type ds(dsSEXP );
        Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP );
        Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP );
        Rcpp::traits::input_parameter< const arma::colvec& >::type gamma(gammaSEXP );
        Rcpp::List __result = sgapca_nnC(ds, Q, x, gamma);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
