# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sgapca_exC <- function(ds, Qs, x, gamma) {
    .Call('onlinePCA_sgapca_exC', PACKAGE = 'onlinePCA', ds, Qs, x, gamma)
}

sgapca_nnC <- function(ds, Q, x, gamma) {
    .Call('onlinePCA_sgapca_nnC', PACKAGE = 'onlinePCA', ds, Q, x, gamma)
}

